# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be4883f020bf88c2597ab6d55be7e8e8"
name = "Leadcod"
application_url = "https://care-seattle-ventures-dried.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
scopes = "read_products,write_orders,write_customers"

[access.admin]
embedded_app_direct_api_access=true

[auth]
redirect_urls = [ "https://care-seattle-ventures-dried.trycloudflare.com/api/auth/api/auth" ]


[[webhooks.subscriptions]]
uri = "/api/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[[webhooks.subscriptions]]
uri = "/api/webhooks/app_subscriptions/update"
topics = ["app_subscriptions/update"]
